server:
  port: 9091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schoolapp
    username: srikanth
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update # You can use "update" or "create-drop" depending on your needs
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# logging:
#   level:
#     org.springframework.boot.autoconfigure.jdbc: DEBUG
#     org.springframework.boot: DEBUG